name: "[PRODUCTION] deploy"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: install build dependencies
        shell: bash
        run: |
          sudo rm /var/lib/man-db/auto-update
          sudo apt update
          sudo apt install --yes podman

      - name: render
        shell: bash
        run: ./run render

      - name: package
        shell: bash
        run: ./run package

      - name: install secrets
        shell: bash
        env:
          ID_RSA:      ${{secrets.ID_RSA}}
          KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
        run: |
          mkdir -p ~/.ssh
          echo "$ID_RSA" > ~/.ssh/id_rsa
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/*

      - name: deploy
        env:
          DOMAIN: ${{vars.DOMAIN}}
          USER:   ${{vars.USER}}
          PORT:   ${{vars.PORT}}
        shell: bash
        run: ./run deploy
